package typings.semanticDashUiDashReact

import typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonMod.StrictButtonProps
import typings.semanticDashUiDashReact.distCommonjsElementsInputInputMod.StrictInputProps
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait semanticDashUiDashReactProps {
  @scala.inline
  def AccordionProps: typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionMod.AccordionProps.type = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionMod.AccordionProps
  type AccordionProps = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionMod.AccordionProps
  @scala.inline
  def AccordionAccordionProps: typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionAccordionMod.AccordionAccordionProps.type = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionAccordionMod.AccordionAccordionProps
  type AccordionAccordionProps = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionAccordionMod.AccordionAccordionProps
  @scala.inline
  def AccordionContentProps: typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionContentMod.AccordionContentProps.type = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionContentMod.AccordionContentProps
  type AccordionContentProps = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionContentMod.AccordionContentProps
  @scala.inline
  def AccordionPanelProps: typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionPanelMod.AccordionPanelProps.type = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionPanelMod.AccordionPanelProps
  type AccordionPanelProps = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionPanelMod.AccordionPanelProps
  @scala.inline
  def AccordionTitleProps: typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionTitleMod.AccordionTitleProps.type = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionTitleMod.AccordionTitleProps
  type AccordionTitleProps = typings.semanticDashUiDashReact.distCommonjsModulesAccordionAccordionTitleMod.AccordionTitleProps
  @scala.inline
  def ButtonProps: StrictButtonProps.type = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonMod.StrictButtonProps
  type ButtonProps = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonMod.ButtonProps
  @scala.inline
  def ButtonContentProps: typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonContentMod.ButtonContentProps.type = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonContentMod.ButtonContentProps
  type ButtonContentProps = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonContentMod.ButtonContentProps
  @scala.inline
  def ButtonGroupProps: typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonGroupMod.ButtonGroupProps.type = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonGroupMod.ButtonGroupProps
  type ButtonGroupProps = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonGroupMod.ButtonGroupProps
  @scala.inline
  def ButtonOrProps: typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonOrMod.ButtonOrProps.type = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonOrMod.ButtonOrProps
  type ButtonOrProps = typings.semanticDashUiDashReact.distCommonjsElementsButtonButtonOrMod.ButtonOrProps
  @scala.inline
  def ContainerProps: typings.semanticDashUiDashReact.distCommonjsElementsContainerContainerMod.ContainerProps.type = typings.semanticDashUiDashReact.distCommonjsElementsContainerContainerMod.ContainerProps
  type ContainerProps = typings.semanticDashUiDashReact.distCommonjsElementsContainerContainerMod.ContainerProps
  @scala.inline
  def InputProps: StrictInputProps.type = typings.semanticDashUiDashReact.distCommonjsElementsInputInputMod.StrictInputProps
  type InputProps = typings.semanticDashUiDashReact.distCommonjsElementsInputInputMod.InputProps
  @scala.inline
  def TestContainerProps: typings.semanticDashUiDashReact.distCommonjsElementsTestContainerTestContainerMod.TestContainerProps.type = typings.semanticDashUiDashReact.distCommonjsElementsTestContainerTestContainerMod.TestContainerProps
  type TestContainerProps = typings.semanticDashUiDashReact.distCommonjsElementsTestContainerTestContainerMod.TestContainerProps
}

