package org.scalablytyped.converter.internal
package scalajs
package flavours

import CastConversion.TParam._1

final class SlinkyWeb(reactNames: ReactNames) {
  val slinkyWeb     = GenSlinkyComponents.names.slinky + Name("web")
  val slinkyWebSvg  = slinkyWeb + Name("svg")
  val slinkyWebHtml = slinkyWeb + Name("html")

  def SlinkyHtmlElement(name: String): TypeRef =
    TypeRef.Singleton(TypeRef(slinkyWebHtml + Name(name) + Name("tag"), Empty, NoComments))

  def SlinkySvgElement(name: String): TypeRef =
    TypeRef.Singleton(TypeRef(slinkyWebSvg + Name(name) + Name("tag"), Empty, NoComments))

  val AnyHtmlElement: TypeRef = SlinkyHtmlElement("*")
  val AnySvgElement:  TypeRef = SlinkySvgElement("*")

  val conversions = IArray(
    CastConversion(reactNames.AnimationEvent, slinkyWeb + Name("SyntheticAnimationEvent"), _1),
    CastConversion(reactNames.ClipboardEvent, slinkyWeb + Name("SyntheticClipboardEvent"), _1),
    CastConversion(reactNames.CompositionEvent, slinkyWeb + Name("SyntheticCompositionEvent"), _1),
    //        CastConversion(reactNames.DragEvent, slinkyWeb + Name("ReactDragEventFrom"), _1Element),
    CastConversion(reactNames.FocusEvent, slinkyWeb + Name("SyntheticFocusEvent"), _1),
    CastConversion(reactNames.KeyboardEvent, slinkyWeb + Name("SyntheticKeyboardEvent"), _1),
    CastConversion(reactNames.MouseEvent, slinkyWeb + Name("SyntheticMouseEvent"), _1),
    CastConversion(reactNames.PointerEvent, slinkyWeb + Name("SyntheticPointerEvent"), _1),
    CastConversion(reactNames.TouchEvent, slinkyWeb + Name("SyntheticTouchEvent"), _1),
    CastConversion(reactNames.TransitionEvent, slinkyWeb + Name("SyntheticTransitionEvent"), _1),
    CastConversion(reactNames.UIEvent, slinkyWeb + Name("SyntheticUIEvent"), _1),
    CastConversion(reactNames.WheelEvent, slinkyWeb + Name("SyntheticWheelEvent"), _1),
  )

  // todo: this was all the mapping i had the energy to do.
  val ElementMapping = Map(
    "HTMLAnchorElement" -> SlinkyHtmlElement("a"),
    "HTMLAppletElement" -> AnyHtmlElement,
    "HTMLAreaElement" -> SlinkyHtmlElement("area"),
    "HTMLAudioElement" -> SlinkyHtmlElement("audio"),
    "HTMLBaseElement" -> SlinkyHtmlElement("base"),
    "HTMLBaseFontElement" -> AnyHtmlElement,
    "HTMLBodyElement" -> SlinkyHtmlElement("body"),
    "HTMLBRElement" -> SlinkyHtmlElement("br"),
    "HTMLButtonElement" -> SlinkyHtmlElement("button"),
    "HTMLCanvasElement" -> SlinkyHtmlElement("canvas"),
    "HTMLDataElement" -> SlinkyHtmlElement("data"),
    "HTMLDataListElement" -> SlinkyHtmlElement("datalist"),
    "HTMLDetailsElement" -> SlinkyHtmlElement("details"),
    "HTMLDialogElement" -> SlinkyHtmlElement("dialog"),
    "HTMLDirectoryElement" -> AnyHtmlElement,
    "HTMLDivElement" -> SlinkyHtmlElement("div"),
    "HTMLDListElement" -> SlinkyHtmlElement("dl"),
    "HTMLElement" -> AnyHtmlElement,
    "HTMLEmbedElement" -> SlinkyHtmlElement("embed"),
    "HTMLFieldSetElement" -> SlinkyHtmlElement("fieldset"),
    "HTMLFontElement" -> AnyHtmlElement,
    "HTMLFormElement" -> SlinkyHtmlElement("form"),
    "HTMLFrameElement" -> AnyHtmlElement,
    "HTMLFrameSetElement" -> AnyHtmlElement,
    "HTMLHeadElement" -> SlinkyHtmlElement("head"),
    "HTMLHeadingElement" -> AnyHtmlElement,
    "HTMLHRElement" -> SlinkyHtmlElement("hr"),
    "HTMLHtmlElement" -> SlinkyHtmlElement("html"),
    "HTMLIFrameElement" -> SlinkyHtmlElement("iframe"),
    "HTMLImageElement" -> SlinkyHtmlElement("img"),
    "HTMLInputElement" -> SlinkyHtmlElement("input"),
    "HTMLLabelElement" -> SlinkyHtmlElement("label"),
    "HTMLLegendElement" -> SlinkyHtmlElement("legend"),
    "HTMLLIElement" -> SlinkyHtmlElement("li"),
    "HTMLLinkElement" -> SlinkyHtmlElement("link"),
    "HTMLMapElement" -> SlinkyHtmlElement("map"),
    "HTMLMarqueeElement" -> AnyHtmlElement,
    "HTMLMediaElement" -> AnyHtmlElement,
    "HTMLMenuElement" -> SlinkyHtmlElement("menu"),
    "HTMLMetaElement" -> SlinkyHtmlElement("meta"),
    "HTMLMeterElement" -> SlinkyHtmlElement("meter"),
    "HTMLModElement" -> AnyHtmlElement,
    "HTMLObjectElement" -> SlinkyHtmlElement("object"),
    "HTMLOListElement" -> SlinkyHtmlElement("ol"),
    "HTMLOptGroupElement" -> SlinkyHtmlElement("optgroup"),
    "HTMLOptionElement" -> SlinkyHtmlElement("option"),
    "HTMLOutputElement" -> SlinkyHtmlElement("output"),
    "HTMLParagraphElement" -> SlinkyHtmlElement("p"),
    "HTMLParamElement" -> SlinkyHtmlElement("param"),
    "HTMLPictureElement" -> SlinkyHtmlElement("picture"),
    "HTMLPreElement" -> SlinkyHtmlElement("pre"),
    "HTMLProgressElement" -> SlinkyHtmlElement("progress"),
    "HTMLQuoteElement" -> SlinkyHtmlElement("q"),
    "HTMLScriptElement" -> SlinkyHtmlElement("script"),
    "HTMLSelectElement" -> SlinkyHtmlElement("select"),
    "HTMLSlotElement" -> AnyHtmlElement,
    "HTMLSourceElement" -> SlinkyHtmlElement("source"),
    "HTMLSpanElement" -> SlinkyHtmlElement("span"),
    "HTMLStyleElement" -> SlinkyHtmlElement("style"),
    "HTMLTableCaptionElement" -> AnyHtmlElement,
    "HTMLTableCellElement" -> AnyHtmlElement,
    "HTMLTableColElement" -> AnyHtmlElement,
    "HTMLTableDataCellElement" -> AnyHtmlElement,
    "HTMLTableElement" -> SlinkyHtmlElement("table"),
    "HTMLTableHeaderCellElement" -> AnyHtmlElement,
    "HTMLTableRowElement" -> AnyHtmlElement,
    "HTMLTableSectionElement" -> AnyHtmlElement,
    "HTMLTemplateElement" -> AnyHtmlElement,
    "HTMLTextAreaElement" -> AnyHtmlElement,
    "HTMLTimeElement" -> AnyHtmlElement,
    "HTMLTitleElement" -> AnyHtmlElement,
    "HTMLTrackElement" -> AnyHtmlElement,
    "HTMLUListElement" -> SlinkyHtmlElement("ul"),
    "HTMLVideoElement" -> AnyHtmlElement,
    "SVGAElement" -> SlinkySvgElement("a"),
    "SVGAnimateElement" -> SlinkySvgElement("animate"),
    "SVGAnimateMotionElement" -> SlinkySvgElement("animateMotion"),
    "SVGAnimateTransformElement" -> SlinkySvgElement("animateTransform"),
    "SVGAnimationElement" -> AnySvgElement,
    "SVGCircleElement" -> SlinkySvgElement("circle"),
    "SVGClipPathElement" -> SlinkySvgElement("clipPath"),
    "SVGComponentTransferFunctionElement" -> AnySvgElement,
    "SVGCursorElement" -> SlinkySvgElement("cursor"),
    "SVGDefsElement" -> SlinkySvgElement("defs"),
    "SVGDescElement" -> SlinkySvgElement("desc"),
    "SVGElement" -> AnySvgElement,
    "SVGEllipseElement" -> SlinkySvgElement("ellipse"),
    "SVGFEBlendElement" -> SlinkySvgElement("feBlend"),
    "SVGFEColorMatrixElement" -> SlinkySvgElement("feColorMatrix"),
    "SVGFEComponentTransferElement" -> AnySvgElement,
    "SVGFECompositeElement" -> AnySvgElement,
    "SVGFEConvolveMatrixElement" -> AnySvgElement,
    "SVGFEDiffuseLightingElement" -> AnySvgElement,
    "SVGFEDisplacementMapElement" -> AnySvgElement,
    "SVGFEDistantLightElement" -> AnySvgElement,
    "SVGFEDropShadowElement" -> AnySvgElement,
    "SVGFEFloodElement" -> AnySvgElement,
    "SVGFEFuncAElement" -> AnySvgElement,
    "SVGFEFuncBElement" -> AnySvgElement,
    "SVGFEFuncGElement" -> AnySvgElement,
    "SVGFEFuncRElement" -> AnySvgElement,
    "SVGFEGaussianBlurElement" -> AnySvgElement,
    "SVGFEImageElement" -> AnySvgElement,
    "SVGFEMergeElement" -> AnySvgElement,
    "SVGFEMergeNodeElement" -> AnySvgElement,
    "SVGFEMorphologyElement" -> AnySvgElement,
    "SVGFEOffsetElement" -> AnySvgElement,
    "SVGFEPointLightElement" -> AnySvgElement,
    "SVGFESpecularLightingElement" -> AnySvgElement,
    "SVGFESpotLightElement" -> AnySvgElement,
    "SVGFETileElement" -> AnySvgElement,
    "SVGFETurbulenceElement" -> AnySvgElement,
    "SVGFilterElement" -> AnySvgElement,
    "SVGForeignObjectElement" -> AnySvgElement,
    "SVGGElement" -> AnySvgElement,
    "SVGGeometryElement" -> AnySvgElement,
    "SVGGradientElement" -> AnySvgElement,
    "SVGGraphicsElement" -> AnySvgElement,
    "SVGImageElement" -> AnySvgElement,
    "SVGLinearGradientElement" -> AnySvgElement,
    "SVGLineElement" -> AnySvgElement,
    "SVGMarkerElement" -> AnySvgElement,
    "SVGMaskElement" -> AnySvgElement,
    "SVGMetadataElement" -> AnySvgElement,
    "SVGPathElement" -> AnySvgElement,
    "SVGPatternElement" -> AnySvgElement,
    "SVGPolygonElement" -> AnySvgElement,
    "SVGPolylineElement" -> AnySvgElement,
    "SVGRadialGradientElement" -> AnySvgElement,
    "SVGRectElement" -> AnySvgElement,
    "SVGScriptElement" -> AnySvgElement,
    "SVGStopElement" -> AnySvgElement,
    "SVGStyleElement" -> AnySvgElement,
    "SVGSVGElement" -> AnySvgElement,
    "SVGSwitchElement" -> AnySvgElement,
    "SVGSymbolElement" -> AnySvgElement,
    "SVGTextContentElement" -> AnySvgElement,
    "SVGTextElement" -> AnySvgElement,
    "SVGTextPathElement" -> AnySvgElement,
    "SVGTextPositioningElement" -> AnySvgElement,
    "SVGTitleElement" -> AnySvgElement,
    "SVGTSpanElement" -> AnySvgElement,
    "SVGUseElement" -> AnySvgElement,
    "SVGViewElement" -> AnySvgElement,
  )

  /* typescript declares more attributes than slinky */
  val attributes: Set[Name] = Set(
    "type",
    "accept",
    "action",
    "alt",
    "aria",
    "async",
    "autoComplete",
    "autoFocus",
    "capture",
    "challenge",
    "checked",
    "className",
    "cols",
    "colSpan",
    "content",
    "contentEditable",
    "controls",
    "coords",
    "dangerouslySetInnerHTML",
    "default",
    "defaultChecked",
    "defaultValue",
    "defer",
    "dir",
    "disabled",
    "download",
    "draggable",
    "headers",
    "height",
    "hidden",
    "high",
    "href",
    "htmlFor",
    "icon",
    "id",
    "integrity",
    "key",
    "kind",
    "lang",
    "list",
    "loop",
    "low",
    "manifest",
    "max",
    "media",
    "method",
    "min",
    "multiple",
    "muted",
    "name",
    "nonce",
    "on",
    "onAbort",
    "onAnimationEnd",
    "onAnimationIteration",
    "onAnimationStart",
    "onBlur",
    "onCancel",
    "onCanPlay",
    "onCanPlayThrough",
    "onChange",
    "onClick",
    "onClose",
    "onCompositionEnd",
    "onCompositionStart",
    "onCompositionUpdate",
    "onContextMenu",
    "onCopy",
    "onCut",
    "onDoubleClick",
    "onDrag",
    "onDragEnd",
    "onDragEnter",
    "onDragExit",
    "onDragLeave",
    "onDragOver",
    "onDragStart",
    "onDrop",
    "onDurationChange",
    "onEmptied",
    "onEncrypted",
    "onEnded",
    "onError",
    "onFocus",
    "onGotPointerCapture",
    "onInput",
    "onInvalid",
    "onKeyDown",
    "onKeyPress",
    "onKeyUp",
    "onLoad",
    "onLoadedData",
    "onLoadedMetadata",
    "onLoadStart",
    "onLostPointerCapture",
    "onMouseDown",
    "onMouseEnter",
    "onMouseLeave",
    "onMouseMove",
    "onMouseOut",
    "onMouseOver",
    "onMouseUp",
    "onPaste",
    "onPause",
    "onPlay",
    "onPlaying",
    "onPointerCancel",
    "onPointerDown",
    "onPointerEnter",
    "onPointerLeave",
    "onPointerMove",
    "onPointerOut",
    "onPointerOver",
    "onPointerUp",
    "onProgress",
    "onRateChange",
    "onScroll",
    "onSeeked",
    "onSeeking",
    "onSelect",
    "onStalled",
    "onSubmit",
    "onSuspend",
    "onTimeUpdate",
    "onToggle",
    "onTouchCancel",
    "onTouchEnd",
    "onTouchMove",
    "onTouchStart",
    "onTransitionEnd",
    "onVolumeChange",
    "onWaiting",
    "onWheel",
    "open",
    "optimum",
    "pattern",
    "placeholder",
    "poster",
    "preload",
    "profile",
    "readOnly",
    "ref",
    "rel",
    "required",
    "reversed",
    "rows",
    "rowSpan",
    "sandbox",
    "scope",
    "scoped",
    "scrolling",
    "selected",
    "shape",
    "size",
    "sizes",
    "spellCheck",
    "src",
    "start",
    "step",
    "suppressContentEditableWarning",
    "tabIndex",
    "target",
    "value",
    "width",
    "wrap",
  ) map Name.apply
}
