package org.scalablytyped.converter.internal.importer

import org.scalablytyped.converter.Selection
import org.scalablytyped.converter.internal.ts.{TsIdentLibrary, TsIdentLibraryScoped, TsIdentLibrarySimple}

object EnabledTypeMappingExpansion {
  val DefaultSelection: Selection[TsIdentLibrary] =
    Selection.NoneExcept(
      TsIdentLibrary("amap-js-api"),
      TsIdentLibrary("antd"),
      TsIdentLibrary("instagram-private-api"),
      TsIdentLibrary("jest-config"),
      TsIdentLibrary("react-autosuggest"),
      TsIdentLibrary("react-dropzone"),
      TsIdentLibrary("react-native"),
      TsIdentLibrary("react-onsenui"),
      TsIdentLibrary("react-select"),
      TsIdentLibraryScoped("ant-design", "colors"),
      TsIdentLibraryScoped("ant-design", "create-react-context"),
      TsIdentLibraryScoped("ant-design", "dark-theme"),
      TsIdentLibraryScoped("ant-design", "icons"),
      TsIdentLibraryScoped("ant-design", "icons-angular"),
      TsIdentLibraryScoped("ant-design", "icons-react"),
      TsIdentLibraryScoped("ant-design", "icons-react-native"),
      TsIdentLibraryScoped("ant-design", "icons-vue"),
      TsIdentLibraryScoped("ant-design", "pro-layout"),
      TsIdentLibraryScoped("ant-design", "react-native"),
      TsIdentLibraryScoped("material-ui", "core"),
      TsIdentLibraryScoped("material-ui", "icons"),
      TsIdentLibraryScoped("material-ui", "lab"),
      TsIdentLibraryScoped("material-ui", "system"),
      TsIdentLibraryScoped("material-ui", "utils"),
      TsIdentLibraryScoped("nivo", "annotations"),
      TsIdentLibraryScoped("nivo", "axes"),
      TsIdentLibraryScoped("nivo", "bar"),
      TsIdentLibraryScoped("nivo", "bullet"),
      TsIdentLibraryScoped("nivo", "calendar"),
      TsIdentLibraryScoped("nivo", "chord"),
      TsIdentLibraryScoped("nivo", "circle-packing"),
      TsIdentLibraryScoped("nivo", "colors"),
      TsIdentLibraryScoped("nivo", "core"),
      TsIdentLibraryScoped("nivo", "generators"),
      TsIdentLibraryScoped("nivo", "geo"),
      TsIdentLibraryScoped("nivo", "heatmap"),
      TsIdentLibraryScoped("nivo", "legends"),
      TsIdentLibraryScoped("nivo", "line"),
      TsIdentLibraryScoped("nivo", "parallel-coordinates"),
      TsIdentLibraryScoped("nivo", "pie"),
      TsIdentLibraryScoped("nivo", "radar"),
      TsIdentLibraryScoped("nivo", "sankey"),
      TsIdentLibraryScoped("nivo", "scales"),
      TsIdentLibraryScoped("nivo", "scatterplot"),
      TsIdentLibraryScoped("nivo", "stream"),
      TsIdentLibraryScoped("nivo", "sunburst"),
      TsIdentLibraryScoped("nivo", "tooltip"),
      TsIdentLibraryScoped("nivo", "treemap"),
      TsIdentLibraryScoped("nivo", "voronoi"),
      TsIdentLibraryScoped("nivo", "waffle"),
      TsIdentLibraryScoped("react-navigation", "core"),
      TsIdentLibraryScoped("react-navigation", "native"),
      TsIdentLibraryScoped("tensorflow", "tfjs"),
      TsIdentLibraryScoped("tensorflow", "tfjs-converter"),
      TsIdentLibraryScoped("tensorflow", "tfjs-core"),
      TsIdentLibraryScoped("tensorflow", "tfjs-data"),
      TsIdentLibraryScoped("tensorflow", "tfjs-layers"),
      TsIdentLibraryScoped("tensorflow", "tfjs-node"),
      TsIdentLibraryScoped("uifabric", "foundation"),
      TsIdentLibraryScoped("uifabric", "icons"),
      TsIdentLibraryScoped("uifabric", "merge-styles"),
      TsIdentLibraryScoped("uifabric", "react-hooks"),
      TsIdentLibraryScoped("uifabric", "set-version"),
      TsIdentLibraryScoped("uifabric", "styling"),
      TsIdentLibraryScoped("uifabric", "utilities"),
      TsIdentLibrarySimple("react-navigation"),
      TsIdentLibrarySimple("react-navigation-drawer"),
      TsIdentLibrarySimple("react-navigation-material-bottom-tabs"),
      TsIdentLibrarySimple("react-navigation-stack"),
      TsIdentLibrary("@storybook/api"),
      TsIdentLibrary("styled-components"),
    )
}
