package typings.semanticDashUiDashReact

import typings.semanticDashUiDashReact.srcElementsButtonButtonMod.StrictButtonProps
import typings.semanticDashUiDashReact.srcElementsInputInputMod.StrictInputProps
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait semanticDashUiDashReactProps {
  @scala.inline
  def AccordionProps: typings.semanticDashUiDashReact.srcModulesAccordionAccordionMod.AccordionProps.type = typings.semanticDashUiDashReact.srcModulesAccordionAccordionMod.AccordionProps
  type AccordionProps = typings.semanticDashUiDashReact.srcModulesAccordionAccordionMod.AccordionProps
  @scala.inline
  def AccordionAccordionProps: typings.semanticDashUiDashReact.srcModulesAccordionAccordionAccordionMod.AccordionAccordionProps.type = typings.semanticDashUiDashReact.srcModulesAccordionAccordionAccordionMod.AccordionAccordionProps
  type AccordionAccordionProps = typings.semanticDashUiDashReact.srcModulesAccordionAccordionAccordionMod.AccordionAccordionProps
  @scala.inline
  def AccordionContentProps: typings.semanticDashUiDashReact.srcModulesAccordionAccordionContentMod.AccordionContentProps.type = typings.semanticDashUiDashReact.srcModulesAccordionAccordionContentMod.AccordionContentProps
  type AccordionContentProps = typings.semanticDashUiDashReact.srcModulesAccordionAccordionContentMod.AccordionContentProps
  @scala.inline
  def AccordionPanelProps: typings.semanticDashUiDashReact.srcModulesAccordionAccordionPanelMod.AccordionPanelProps.type = typings.semanticDashUiDashReact.srcModulesAccordionAccordionPanelMod.AccordionPanelProps
  type AccordionPanelProps = typings.semanticDashUiDashReact.srcModulesAccordionAccordionPanelMod.AccordionPanelProps
  @scala.inline
  def AccordionTitleProps: typings.semanticDashUiDashReact.srcModulesAccordionAccordionTitleMod.AccordionTitleProps.type = typings.semanticDashUiDashReact.srcModulesAccordionAccordionTitleMod.AccordionTitleProps
  type AccordionTitleProps = typings.semanticDashUiDashReact.srcModulesAccordionAccordionTitleMod.AccordionTitleProps
  @scala.inline
  def ButtonProps: StrictButtonProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonMod.StrictButtonProps
  type ButtonProps = typings.semanticDashUiDashReact.srcElementsButtonButtonMod.ButtonProps
  @scala.inline
  def ButtonContentProps: typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps
  type ButtonContentProps = typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps
  @scala.inline
  def ButtonGroupProps: typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps
  type ButtonGroupProps = typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps
  @scala.inline
  def ButtonOrProps: typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps
  type ButtonOrProps = typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps
  @scala.inline
  def ContainerProps: typings.semanticDashUiDashReact.srcElementsContainerContainerMod.ContainerProps.type = typings.semanticDashUiDashReact.srcElementsContainerContainerMod.ContainerProps
  type ContainerProps = typings.semanticDashUiDashReact.srcElementsContainerContainerMod.ContainerProps
  @scala.inline
  def ContentProps: typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps
  type ContentProps = typings.semanticDashUiDashReact.srcElementsButtonButtonContentMod.ButtonContentProps
  @scala.inline
  def GroupProps: typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps
  type GroupProps = typings.semanticDashUiDashReact.srcElementsButtonButtonGroupMod.ButtonGroupProps
  @scala.inline
  def InputProps: StrictInputProps.type = typings.semanticDashUiDashReact.srcElementsInputInputMod.StrictInputProps
  type InputProps = typings.semanticDashUiDashReact.srcElementsInputInputMod.InputProps
  @scala.inline
  def OrProps: typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps.type = typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps
  type OrProps = typings.semanticDashUiDashReact.srcElementsButtonButtonOrMod.ButtonOrProps
  @scala.inline
  def TestContainerProps: typings.semanticDashUiDashReact.srcElementsTestContainerTestContainerMod.TestContainerProps.type = typings.semanticDashUiDashReact.srcElementsTestContainerTestContainerMod.TestContainerProps
  type TestContainerProps = typings.semanticDashUiDashReact.srcElementsTestContainerTestContainerMod.TestContainerProps
}

