package ScalablyTyped
package ReactDashBootstrapLib.ReactDashBootstrapModule

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object ToggleButtonGroupNamespace {
  type BaseProps = ReactDashBootstrapLib.ReactDashBootstrapLibToggleButtonGroupModule.ToggleButtonGroupNamespace.BaseProps
  type CheckboxProps = ReactDashBootstrapLib.ReactDashBootstrapLibToggleButtonGroupModule.ToggleButtonGroupNamespace.CheckboxProps
  type RadioProps = ReactDashBootstrapLib.ReactDashBootstrapLibToggleButtonGroupModule.ToggleButtonGroupNamespace.RadioProps
  type ToggleButtonGroup = ReactDashBootstrapLib.ReactDashBootstrapLibToggleButtonGroupModule.ToggleButtonGroup
  type ToggleButtonGroupProps = ReactDashBootstrapLib.ReactDashBootstrapLibToggleButtonGroupModule.ToggleButtonGroupNamespace.ToggleButtonGroupProps
}
